apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taskflow
        app.kubernetes.io/component: front
    spec:
      containers:
        - name: front
          image: antony35/taskflow-front:1.1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
spec:
  selector:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: front
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
  type: LoadBalancer
