apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: api
spec:
  containers:
    - name: api
      image: antony35/taskflow-api:1.0.0
      env:
        - name: DB_PASSWORD
          value: test
        - name: DB_HOST
          value: 10.42.0.21
      ports:
        - containerPort: 3000
