apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: db
spec:
  containers:
    - name: db
      image: postgres:18.6-alpine3.24
      env:
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_USER
          value: taskflow
        - name: POSTGRES_DB
          value: taskflow
      ports:
        - containerPort: 5432
